config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :ideas

  root 'welcome#index'

     resources :ideas

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_one :user, as: :account
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :ideas_manager
  has_many :votes, as: :voteable
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 10 }
end

app/models/ideas_manager.rb
class IdeasManager < ActiveRecord::Base
  has_many :ideas
  has_many :votes
  has_many :comments
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'MessagesManager'
  belongs_to :receiver, :class_name => 'MessagesManager'
end

app/models/messages_manager.rb
class MessagesManager < ActiveRecord::Base
	belongs_to :user
	has_many :notes
	has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'
	has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :messages_manager
end

app/models/super_user.rb
class SuperUser < ActiveRecord::Base
  has_one :user, as: :account
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  belongs_to :account, polymorphic: true
  has_and_belongs_to_many :user_groups
  has_one :messages_manager	

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
  belongs_to :ideas_manager
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_action :configure_devise_params, if: :devise_controller?

  protected

  def configure_devise_params
  	devise_parameter_sanitizer.for(:sign_up) << :firstname << :lastname
  	devise_parameter_sanitizer.for(:account_update) << :firstname << :lastname
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def new
		@idea = Idea.new
	end

	def create
	  @idea = Idea.new(idea_params)
	 
	  if @idea.save
	  	redirect_to @idea
	  else
	  	render 'new'
	  end
	end

	def show
	  @idea = Idea.find(params[:id])
	end

	def index
	  @ideas = Idea.all
	end	

	def edit
	  @idea = Idea.find(params[:id])
	end	

	def update
	  @idea = Idea.find(params[:id])
	 
	  if @idea.update(idea_params)
	    redirect_to @idea
	  else
	    render 'edit'
	  end
	end

	private
	  def idea_params
	    params.require(:idea).permit(:title, :description)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index 
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	unless @user == current_user
  		redirect_to :back, alert: "Access denied".
  	end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_form.html.erb
<%= form_for :idea, url: ideas_path do |f| %>
  <% if @idea.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@idea.errors.count, "error") %> some errors occured while saving this idea:</h2>
    <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea!</h1>
 
<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>All Ideas review</h1>
 
<table>
  <tr>
    <th>Idea's title</th>
    <th>Description</th>
    <th colspan="2">Action</th>
  </tr>
 
  <% @ideas.each do |idea| %>
    <tr>
      <td><%= idea.title %></td>
      <td><%= idea.description %></td>
      <td><%= link_to 'Show', idea_path(idea) %></td>
      <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    </tr>
  <% end %>
</table>

app/views/ideas/new.html.erb
<h1>New Idea!</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<p>
  <strong>Idea's title:</strong>
  <%= @idea.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomysłodajnia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  
</head>
<body id="page-top" class="index" data-spy="scroll" data-target=".navbar-fixed-top">
<%= yield %>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomysłodajnia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  
</head>
<body id="page-top" class="index" data-spy="scroll" data-target=".navbar-fixed-top">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><%= image_tag("profile.png", :alt => "", class: 'logo-small') %>Pomysłodajnia </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="/"></a>
                </li>
                <li class="page-scroll">
                    <a href="#about">O Pomysłodajni</a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Portfolio BIT IF</a>
                </li>
                <li class="page-scroll">
                    <a href="#contact">Kontakt</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

  <header class="full-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  <header>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Zaloguj się", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Zarejestruj się", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Zapomniałeś hasła?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Nie otrzymałeś potwierdzenia maila?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Nie otrzmyałeś instrukcji odblokowania konta?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>